version: '3'
services:

  db:
    container_name: nuxt-rails-db
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./tmp/db/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password2020!

  app:
    build: .
    container_name: nuxt-rails-app
    command: bundle exec pumactl start
    volumes:
      - .:/nuxt-rails-api-sampler
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RAILS_ENV: development

# volumes:
#   sockets:
