version: '3'
services:

  db:
    container_name: rails-db
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./backend/tmp/db/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password2020!

  backend:
    build: backend/
    container_name: rails-app
    command: bundle exec pumactl start
    volumes:
      - ./backend:/nuxt-rails-api-sampler/backend
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    
  frontend:
    build: frontend/
    container_name: nuxt-app
    command: npm run dev
    ports:
      - 8000:3000
    volumes:
      - ./frontend:/nuxt-rails-api-sampler/frontend
    depends_on:
      - backend
